spring:
  application:
    name: oj
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    # store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oj
    username: root
    password: 123456
  # Redis 配置
  redis:
    database: 2
    host: localhost
    port: 6379
    timeout: 5000
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  # 文件上传
  servlet:
    multipart:
      max-file-size: 10MB
server:
  address: 0.0.0.0
  port: 8121
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# 代码沙箱配置
codeSandbox:
  type: local

tencent:
  sms:
    # 腾讯云账户 secrtId，secretKey
    secretId:
    keysecret:
    # 短信应用ID：短信SdkAppId在 【短信控制台】添加应用后生成实际的SdkAppId
    smsSdkAppId:
    # 短信签名内容：
    signName:
    # 模板ID：必须是已经审核通过的模板ID
    templateId:

cos:
  client:
    accessKey:
    secretKey:
    region:
    bucket:

